---
include:
  - board: seeeduino_xiao_ble
    shield: zorne_left
  - board: seeeduino_xiao_ble
    shield: zorne_right
  - board: seeeduino_xiao_ble
    shield: zorne_dongle
  - board: seeeduino_xiao_ble
    shield: settings_reset
